name: FirstPlugin
version: 1.0
author: Randy
main: me.randy.firstplugin.Main
description: My first plugin
commands:
  start:
    aliases: [begin]
    description: "starts the deathswap game"
  end:
    aliases: [finish]
    description: "ends the deathswap game"